Os_based deployment

- name: Deploy Elastic Agent
  hosts: all
  gather_facts: yes
  vars:
    fleet_server_url: "https://192.168.1.11:8220"
    enrollment_token: "{{ lookup('env', 'ELASTIC_AGENT_ENROLLMENT_TOKEN') }}"
    elastic_agent_version: "8.10.4"
    windows_install_dir: "C:\\Program Files\\Agent"
    kali_download_dir: "/home/kali/Downloads"
    ansible_winrm_operation_timeout_sec: 60
    ansible_winrm_read_timeout_sec: 70
    general_token: "SWxGMnBwQUI1UUFmSEt6N1d2VUk6MlNxNmRTMTFSLUdXdzBhZGU3QmQyQQ=="
    heavy_token: "SkZGMnBwQUI1UUFmSEt6N1pmWHc6ZmJvUFBsOWZTRy1uZ3E4di1ERWZKZw=="
  tasks:
    - name: Set OS-specific variables
      set_fact:
        is_windows: "{{ ansible_os_family == 'Windows' }}"
        is_kali: "{{ ansible_distribution == 'Kali' }}"

    - name: Deploy Elastic Agent on Kali Linux
      block:
        - name: Download Elastic Agent for Kali Linux
          get_url:
            url: "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{{ elastic_agent_version }}-linux-x86_64.tar.gz"
            dest: "{{ kali_download_dir }}/elastic-agent-{{ elastic_agent_version }}-linux-x86_64.tar.gz"
            validate_certs: no
          register: download_result

        - name: Debug download result
          debug:
            var: download_result

        - name: Extract Elastic Agent
          unarchive:
            src: "{{ kali_download_dir }}/elastic-agent-{{ elastic_agent_version }}-linux-x86_64.tar.gz"
            dest: "{{ kali_download_dir }}"
            remote_src: yes
          register: extract_result

        - name: Debug extract result
          debug:
            var: extract_result

        - name: Install and start Elastic Agent
          command:
            cmd: "{{ kali_download_dir }}/elastic-agent-{{ elastic_agent_version }}-linux-x86_64/elastic-agent install -f --url={{ fleet_server_url }} --enrollment-token={{ general_token }} --insecure"
          become: yes

        - name: Ensure Elastic Agent service is started
          systemd:
            name: elastic-agent
            state: started
            enabled: yes
          become: yes

      when: is_kali

    - name: Deploy Elastic Agent on Windows
      block:
        - name: Download Elastic Agent for Windows
          win_get_url:
            url: "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{{ elastic_agent_version }}-windows-x86_64.zip"
            dest: "{{ windows_install_dir }}\\elastic-agent.zip"
            validate_certs: no

        - name: Extract Elastic Agent
          win_unzip:
            src: "{{ windows_install_dir }}\\elastic-agent.zip"
            dest: "{{ windows_install_dir }}\\elastic-agent"
            delete_archive: yes

        - name: Install Elastic Agent
          win_shell: |
            cd "{{ windows_install_dir }}\\elastic-agent\\elastic-agent-{{ elastic_agent_version }}-windows-x86_64"
            .\\elastic-agent.exe install --url={{ fleet_server_url }} --enrollment-token={{ heavy_token }} --insecure -f

        - name: Ensure Elastic Agent service is running
          win_service:
            name: elastic-agent
            start_mode: auto
            state: started

      when: is_windows